services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: rentalos
      POSTGRES_USER: rentalos
      POSTGRES_PASSWORD: rentalos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"

  api:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm i && npm run start:dev"
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://rentalos:rentalos@postgres:5432/rentalos
      STORAGE_DRIVER: filesystem
      STORAGE_BASE_PATH: /storage
      GOTENBERG_URL: http://gotenberg:3000
      JWT_SECRET: change_me_dev_secret
      SMTP_HOST: smtp-relay.brevo.com
      SMTP_PORT: 587
      SMTP_USER: a13280001@smtp-brevo.com
      SMTP_PASS: J6HWPSyUNCYwmfFq
      SMTP_FROM: "RentalOS <no-reply@rentalos.fr>"

    volumes:
      - ../apps/api:/app
      - ../infra/storage:/storage
      - ../packages:/packages
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - gotenberg


  pgadmin:
    image: dpage/pgadmin4
    container_name: infra-pgadmin-1
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rentalos.fr
      PGADMIN_DEFAULT_PASSWORD: "ChangeMe_123!"
    depends_on:
      - postgres

  web:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm i && npm run build && npm run start -- -p 3000"
    environment:
      NEXT_PUBLIC_API_URL: /api
    volumes:
      - ../apps/web:/app
      - ../packages:/packages
    ports:
      - "3001:3000"
    depends_on:
      - api

volumes:
  pgdata:
